server:
  port: 1111

spring:
  application:
    name: USER_SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/exam_portal
    username: root
    password: Admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}   # Use environment variable
    password: ${MAIL_PASSWORD}   # Use environment variable
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
